# Generated by Django 3.2.12 on 2022-04-19 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_tag_usertag'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='model',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
